export const ADD_NEWS = 'ADD_NEWS'
export const DELETE_NEWS = 'DELETE_NEWS'
export const ADD_COMMENTS = 'ADD_COMMENTS'
export const ADD_CATEGORY = 'ADD_CATEGORY'
export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'
export const LOG_IN_FAILURE = 'LOG_IN_FAILURE'
export const LIKE = 'LIKE'
